version: '3'

services:
  api:
    image: ruby:3.2
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "bundle install && ruby app.rb -p 3000 -o 0.0.0.0"
    ports:
      - "3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    ports:
      - "9999:9999"
    depends_on:
      - api